---

fail_fast: false

repos:

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.11.1
    hooks:
      - id: yamllint
        args: ['--format', 'parsable', '--strict']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: detect-private-key

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.7.1
    hooks:
      - id: shellcheck
      - id: forbid-binary
      - id: git-check  # Configure in .gitattributes
      - id: git-dirty  # Configure in .gitignore
      - id: reek
        additional_dependencies: [json_pure, memoist2]
      - id: rubocop
        additional_dependencies: [json_pure, memoist2]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.5
    hooks:
      - id: forbid-crlf
      - id: forbid-tabs
